backend:
  name: github
  repo: lemodragon/homepages 
  branch: main
  base_url: https://lvdpub.com
  auth_endpoint: api/auth/callback

media_folder: "static/img"
public_folder: "/static/img"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - label: "Site Settings"
        name: "site_settings"
        file: "content/site-settings.json"
        fields:
          - {label: "Site Title", name: "siteTitle", widget: "string"}
          - {label: "Logo Image", name: "logoImage", widget: "image"}
          - {label: "Footer Text", name: "footerText", widget: "string"}
          - {label: "Background Image", name: "backgroundImage", widget: "image"}
          - label: "Tags"
            name: "tags"
            widget: "list"
            field: {label: Tag, name: tag, widget: string}
          - label: "Timeline"
            name: "timeline"
            widget: "list"
            fields:
              - {label: "Event", name: "event", widget: "string"}
              - {label: "Date", name: "date", widget: "string"}
  
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.json"
        fields:
          - {label: "Welcome Text", name: "welcome", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - label: "Social Links"
            name: "socialLinks"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}